[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
chess-core = { path = "../chess-core" }
engine = { path = "../engine"}


tokio        = { version = "1.45.0", features = ["full"] }
tokio-stream = "0.1"
reqwest      = { version = "0.12", features = ["json", "stream"] }
anyhow       = "1.0"
licheszter   = "0.4"
futures-util = "0.3"
dotenv = "0.15.0"
serde = "1.0.219"
serde_json = "1.0.142"
futures = "0.3"


rand = "0.10.2"